
### FIND ONE USER
GET http://localhost:3001/users/Adam


### FIND ALL USERS BELOW

GET http://localhost:3001/users/


### POST FOR SIGN UP BELOW

POST http://localhost:3001/users/register
Content-Type: application/json
    
{
    "username": "Adamm",
    "password": "123",
    "email": "lars@myspace.com"
}

### POST FOR LOG IN UP BELOW


POST http://localhost:3001/login
Content-Type: application/json
    
{
    "username": "Adam",
    "password": "123"
}

###

# PUT http://localhost:3001/users/Ragny
# Content-Type: application/json
    
# {
#     "username": "TurboRagny",
#     "password": "123",
#     "email": "goranpersson@myspace.com"
#  }

# ### DELETE A USER BELOW

# DELETE http://localhost:3001/users/linnea

### SIGN OUT

DELETE http://localhost:3001/logout

###
