
GET http://localhost:3001/users


### FIND ALL USERS BELOW

GET http://localhost:3001/users

### POST FOR SIGN UP BELOW

POST http://localhost:3001/users/register
Content-Type: application/json
    
{
    "username": "zlatan",

    "password": "123",
    "email": "goranpersson@myspace.com"
}

### POST FOR LOG IN UP BELOW


POST http://localhost:3001/login
Content-Type: application/json
    
{
    "username": "zlatan",
    "password": "123",
    "email": "goranpersson@myspace.com"

}

###

PUT http://localhost:3001/users/granprsn
Content-Type: application/json
    
    {
    "username": "Göran",
    "password": "123",
    "email": "goranpersson@myspace.com"
    }

### DELETE A USER BELOW

DELETE http://localhost:3001/users/granprsn

### SIGN OUT

DELETE http://localhost:3001/logout

