
GET http://localhost:3001/users


###

GET http://localhost:3001/users

###

POST http://localhost:3001/users/register
Content-Type: application/json
    
{
    "username": "zlatan",
    "password": "123",
    "email": "theoneandonly@myspace.com",
    "admin": true
}

###

PUT http://localhost:3001/users/granprsn
Content-Type: application/json
    
    {
    "username": "Göran",
    "password": "123",
    "email": "goranpersson@myspace.com",
    "admin": false
    }

###

DELETE http://localhost:3001/users/granprsn