
GET http://localhost:3001/wallposts

###

POST http://localhost:3001/wallposts/newpost
Content-Type: application/json

{
    "body": "Lång dag på jobbet"
}

### PUT STILL NOT UPDATING CORRECTLY


PUT http://localhost:3001/wallposts/62824fc9d2611d3726e061d8
Content-Type: application/json

{
    "body": "Hej hopp gummisnopp"
}

###


DELETE http://localhost:3001/wallposts/62824fc9d2611d3726e061d8

