
GET http://localhost:3001/wallposts

###

POST http://localhost:3001/wallposts/newpost
Content-Type: application/json

{
    "username": "Ragny",
    "body": "Lång dag på jobbet. USCH! Jag längtar efter melodikrysset. Mvh Ragny"

}

### PUT STILL NOT UPDATING CORRECTLY


PUT http://localhost:3001/wallposts/27fab4dc92ff18c10a464a6
Content-Type: application/json

{
    "username": "Lollipop",
    "body": "Hej hopp!!"

}

###


DELETE http://localhost:3001/wallposts/627fab4dc92ff18c10a464a6

